apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  name: pod-creator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-creator-role
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - restricted # Pod Security Policy Name
- apiGroups: ['']
  resources: ['pods']
  verbs:     ['create','update','patch','get','list','delete','watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-creator-rolebinding
roleRef:
  kind: Role
  name: pod-creator-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: pod-creator
