apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-valid
spec:
  selector:
    matchLabels:
      app: deployment-valid
  replicas: 3
  template:
    metadata:
      labels:
        app: deployment-valid
    spec:
      serviceAccountName: runner
      hostPID: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 3000
      containers:
      - name: pause
        image: k8s.gcr.io/pause
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
