apiVersion: v1
kind: Pod
metadata:
  name: pod-violation-escalation
spec:
  hostPID: false
  containers:
  - name:  pause
    image: k8s.gcr.io/pause
    securityContext:
      allowPrivilegeEscalation: true
      privileged: false
      runAsUser: 1000
      runAsGroup: 3000
