apiVersion: v1
kind: Pod
metadata:
  name: pod-violation-hostpid
spec:
  hostPID: true
  containers:
  - name:  pause
    image: k8s.gcr.io/pause
    securityContext:
      allowPrivilegeEscalation: false
      privileged: false
      runAsUser: 1000
      runAsGroup: 3000
