---
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  name: runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: runner-role
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - restricted
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runner-rolebinding
roleRef:
  kind: Role
  name: runner-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: runner
---
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  name: deployer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer-role
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - restricted
- apiGroups: ['']
  resources: ['serviceaccounts']
  verbs:     ['use']
  resourceNames:
  - runner # to be able to use the runner service account
- apiGroups: ['']
  resources: ['pods']
  verbs:     ['get','list','delete','watch']
- apiGroups: ['']
  resources: ['events']
  verbs:     ['list']
- apiGroups: ['apps']
  resources: ['deployments','replicasets']
  verbs:     ['get','create','list','delete','watch','update','patch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-rolebinding
roleRef:
  kind: Role
  name: deployer-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: deployer
