apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer-role
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - restricted # Pod Security Policy Name
- apiGroups: ['']
  resources: ['serviceaccounts']
  verbs:     ['use']
  resourceNames:
  - runner # Runner service account name
- apiGroups: ['']
  resources: ['pods']
  verbs:     ['get','list','delete','watch']
- apiGroups: ['']
  resources: ['events']
  verbs:     ['list']
- apiGroups: ['apps']
  resources: ['deployments','replicasets']
  verbs:     ['get','create','list','delete','watch','update','patch']
