apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-rolebinding
roleRef:
  kind: Role
  name: deployer-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: deployer
