apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer-role
rules:
- apiGroups: ['']
  resources: ['serviceaccounts']
  verbs:     ['use']
  resourceNames:
  - runner # to be able to use the runner service account
- apiGroups: ['']
  resources: ['pods']
  verbs:     ['get','list','delete','watch']
- apiGroups: ['']
  resources: ['events']
  verbs:     ['list']
- apiGroups: ['apps']
  resources: ['deployments','replicasets']
  verbs:     ['get','create','list','delete','watch','update','patch']
